FROM nginx:1.25.4-alpine

# Copy custom configuration if needed
# COPY nginx.conf /etc/nginx/nginx.conf

# Copy website files
# COPY ./html /usr/share/nginx/html

# Expose port 80
EXPOSE 80


# Use the default nginx command to start Nginx
CMD ["nginx", "-g", "daemon off;"]