apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-eksctl-cluster
  region: us-east-1
  version: "1.30"

# Minimal development cluster configuration
vpc:
  autoAllocateIPv6: false

managedNodeGroups:
  - name: dev-nodes
    instanceType: t3.micro
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 20
    volumeType: gp3
    amiFamily: AmazonLinux2
    ssh:
      enableSsm: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        albIngress: true

# Essential add-ons only for development
addons:
  - name: vpc-cni
    version: latest
  - name: coredns  
    version: latest
  - name: kube-proxy
    version: latest

# Minimal logging for cost optimization
cloudWatch:
  clusterLogging:
    enable: ["api", "audit"]
    logRetentionInDays: 1